version: "3.7"

services:
    db:
        image: "mariadb:bionic"
        container_name: "rathena_db"
        ports:
            - "3306:3306" # allow DB connections from host
        volumes:
            - "rathenadb:/var/lib/mysql" # save database to local disk
            - "./sql-files/:/docker-entrypoint-initdb.d" # initialize db with ./sql-files
        environment:
            MYSQL_ROOT_PASSWORD: ragnarok
            MYSQL_DATABASE: ragnarok
            MYSQL_USER: ragnarok
            MYSQL_PASSWORD: ragnarok
    server:
        image: "rathena:local"
        container_name: "rathena"
        ports:
            - "5121:5121" # map server
            - "6121:6121" # char server
            - "6900:6900" # login server
        volumes:
            - ".:/rathena" # mount directory inside container
            - "./tools/docker_db.conf:/rathena/conf/import/inter_conf.txt" # load db connection
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db

volumes:
    rathenadb:
